/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */

import {
  imageOne,
  imageTwo,
  imageThree,
  imageFour,
  imageFive,
  imageSix,
  imageSeven,
  imageEight,
  imageNine,
  imageTen,
  imageEleven,
  imageTwelve,
} from "../../assets/";

export const videos = [
  {
    _id: "Wo5dMEP_BbI",
    title:
      "After watching this, your brain will not be the same | Lara Boyd | TEDxVancouver",
    youtubeId: "LNHBMFCzznE",
    videoLength: "14:24",
    thumbnail: imageOne,
    likes: "398K",
    views: "34M",
    subscribers: "40M",
    category: "psychology",
    channelName: "TedX",
    channelLink: "https://www.youtube.com/channel/UCsT0YIqwnpJCM-mx7-gSA4Q",
    channelLogo:
      "https://yt3.ggpht.com/ytc/AKedOLQGnY6McntoY-eWaRDI047FWFqj7pVlw2nBfkwz7w=s68-c-k-c0x00ffffff-no-rj",
    description:
      "In a classic research-based TEDx Talk, Dr. Lara Boyd describes how neuroplasticity gives you the power to shape the brain you want.",
    isFeatured: false,
    isTrending: false,
  },
  {
    _id: "Wo5dMEP_BbA",
    title:
      "After watching this, your brain will not be the same | Lara Boyd | TEDxVancouver",
    youtubeId: "qYvXk_bqlBk",
    videoLength: "15:16",
    thumbnail: imageTwo,
    likes: "238K",
    views: "90M",
    subscribers: "60M",
    category: "psychology",
    channelName: "Ted Talks",
    channelLink: "https://www.youtube.com/channel/UCAuUUnT6oDeKwE6v1NGQxug",
    channelLogo:
      "https://yt3.ggpht.com/ytc/AKedOLSAltH3yarKh0eytWLSLtB9-kPpMLM5EejH-GAZIg=s88-c-k-c0x00ffffff-no-rj",
    description:
      "What makes you, you? Psychologists like to talk about our traits, or defined characteristics that make us who we are.",
    isFeatured: false,
    isTrending: false,
  },
  {
    _id: "Wo5dMEP_BbB",
    title: "Are all of your memories real? - Daniel L. Schacter",
    youtubeId: "D-2p86FvqF4",
    videoLength: "5:17",
    thumbnail: imageThree,
    likes: "54K",
    views: "1.5M",
    subscribers: "30M",
    category: "psychology",
    channelName: "Ted-Ed",
    channelLink: "https://www.youtube.com/channel/UCsooa4yRKGN_zEE8iknghZA",
    channelLogo:
      "https://yt3.ggpht.com/HjXKmDGoAp6b-JdGYpqJYYeN4S_CMpD_kqWvldpN53cbzn-i73t6mVNo8mNki-xLPwi0BVSFi-o=s88-c-k-c0x00ffffff-no-rj",
    description:
      "Dig into the psychology of how memories are susceptible to false information and why we shouldn’t treat them as truth.",
    isFeatured: false,
    isTrending: false,
  },
  {
    _id: "Wo5dMEP_BbC",
    title: "Time management tips for students and working professionals! ",
    youtubeId: "op_jwGT6Bvc",
    videoLength: "13:11",
    thumbnail: imageFour,
    likes: "30K",
    views: "5M",
    subscribers: "20M",
    category: "time-management",
    channelName: "Warikoo",
    channelLink: "https://www.youtube.com/channel/UCRzYN32xtBf3Yxsx5BvJWJw",
    channelLogo:
      "https://yt3.ggpht.com/X9eoDIB9cgb1s-kvATRs1lQDcU4Fjc15NDV9s9FF8ck7IsA8u7OdijaernoDV9LLdePgjlt_=s88-c-k-c0x00ffffff-no-rj",
    description:
      "In this video, I will share three tips to manage your time. You will not have to force yourself, nor will you have to do what I do.",
    isFeatured: true,
    isTrending: false,
  },
  {
    _id: "Wo5dMEP_BbD",
    title: "SMART WORK & TIME MANAGEMENT IN HINDI",
    youtubeId: "QhGvLnV5QSY",
    videoLength: "10:46",
    thumbnail: imageFive,
    likes: "60K",
    views: "1.5M",
    subscribers: "50M",
    category: "time-management",
    channelName: "Seeken",
    channelLink: "https://www.youtube.com/channel/UCfhbydY40P2Lli9HuBz8cdA",
    channelLogo:
      "https://yt3.ggpht.com/ytc/AKedOLTAoqk7oUQEP-jf3bZh1embvt-G2qyyI6XM09o9UA=s88-c-k-c0x00ffffff-no-rj",
    description:
      "3 SIMPLE TIME MANAGEMENT TIPS IN HINDI - EAT THAT FROG BY BRIAN TRACY ANIMATED BOOK SUMMARY",
    isFeatured: true,
    isTrending: false,
  },
  {
    _id: "Wo5dMEP_BbE",
    title:
      "How to manage your time more effectively (according to machines) - Brian Christian",
    youtubeId: "iDbdXTMnOmE",
    videoLength: "5:09",
    thumbnail: imageSix,
    likes: "151K",
    views: "5.1M",
    subscribers: "30M",
    category: "time-management",
    channelName: "Ted-Ed",
    channelLink: "https://www.youtube.com/channel/UCsooa4yRKGN_zEE8iknghZA",
    channelLogo:
      "https://yt3.ggpht.com/HjXKmDGoAp6b-JdGYpqJYYeN4S_CMpD_kqWvldpN53cbzn-i73t6mVNo8mNki-xLPwi0BVSFi-o=s88-c-k-c0x00ffffff-no-rj",
    description:
      "Over the last fifty or so years, computer scientists have learned a lot of good strategies for managing time effectively — and they have a lot of experience with what can go wrong. Brian Christian shares how we can use some of these insights to help make the most of our own lives.",
    isFeatured: true,
    isTrending: false,
  },
  {
    _id: "Wo5dMEP_BbF",
    title: "Teach life skills and change our world: Jill Siegal Chalsty",
    youtubeId: "Azy6DD2bDHg",
    videoLength: "11:20",
    thumbnail: imageSeven,
    likes: "1K",
    views: "90K",
    subscribers: "40M",
    category: "life-skills",
    channelName: "TedX",
    channelLink: "https://www.youtube.com/channel/UCsT0YIqwnpJCM-mx7-gSA4Q",
    channelLogo:
      "https://yt3.ggpht.com/ytc/AKedOLQGnY6McntoY-eWaRDI047FWFqj7pVlw2nBfkwz7w=s88-c-k-c0x00ffffff-no-rj",
    description:
      "Jill Chalsty says the way to help young people succeed in the classroom and beyond, is to build their schooling on a strong foundation of communication, decision-making and goal setting tools.",
    isFeatured: true,
    isTrending: false,
  },
  {
    _id: "Wo5dMEP_BbG",
    title: "How simple ideas lead to scientific discoveries",
    youtubeId: "F8UFGu2M2gM",
    videoLength: "07:31",
    thumbnail: imageEight,
    likes: "43K",
    views: "20K",
    subscribers: "30M",
    category: "science",
    channelName: "Ted-Ed",
    channelLink: "https://www.youtube.com/channel/UCsooa4yRKGN_zEE8iknghZA",
    channelLogo:
      "https://yt3.ggpht.com/HjXKmDGoAp6b-JdGYpqJYYeN4S_CMpD_kqWvldpN53cbzn-i73t6mVNo8mNki-xLPwi0BVSFi-o=s88-c-k-c0x00ffffff-no-rj",
    description:
      "Adam Savage walks through two spectacular examples of profound scientific discoveries that came from simple, creative methods anyone could have followed",
    isFeatured: true,
    isTrending: false,
  },
  {
    _id: "Wo5dMEP_BbJ",
    title:
      "The fascinating places scientists aren't exploring | Ella Al-Shamahi",
    youtubeId: "xgW-0egOWVg",
    videoLength: "15:53",
    thumbnail: imageNine,
    likes: "4.1K",
    views: "1.3M",
    subscribers: "60M",
    category: "science",
    channelName: "Ted Talks",
    channelLink: "https://www.youtube.com/channel/UCAuUUnT6oDeKwE6v1NGQxug",
    channelLogo:
      "https://yt3.ggpht.com/ytc/AKedOLSAltH3yarKh0eytWLSLtB9-kPpMLM5EejH-GAZIg=s88-c-k-c0x00ffffff-no-rj",
    description:
      "We're not doing frontline exploratory science in a huge portion of the world -- the places governments deem too hostile or disputed. What might we be missing because we're not looking? ",
    isFeatured: false,
    isTrending: true,
  },
  {
    _id: "Wo5dMEP_BbK",
    title: "Learning how to learn | Barbara Oakley ",
    youtubeId: "O96fE1E-rf8",
    videoLength: "17:50",
    thumbnail: imageTen,
    likes: "42K",
    views: "1.9M",
    subscribers: "40M",
    category: "learning",
    channelName: "TedX",
    channelLink: "https://www.youtube.com/channel/UCsT0YIqwnpJCM-mx7-gSA4Q",
    channelLogo:
      "https://yt3.ggpht.com/ytc/AKedOLQGnY6McntoY-eWaRDI047FWFqj7pVlw2nBfkwz7w=s88-c-k-c0x00ffffff-no-rj",
    description: "Learning How To Learn.. The Concept that most don't know",
    isFeatured: true,
    isTrending: false,
  },
  {
    _id: "Wo5dMEP_BbL",
    title: "The first 20 hours -- how to learn anything | Josh Kaufman",
    youtubeId: "5MgBikgcWnY",
    videoLength: "19:26",
    thumbnail: imageEleven,
    likes: "670K",
    views: "30M",
    subscribers: "40M",
    category: "learning",
    channelName: "TedX",
    channelLink: "https://www.youtube.com/channel/UCsT0YIqwnpJCM-mx7-gSA4Q",
    channelLogo:
      "https://yt3.ggpht.com/ytc/AKedOLQGnY6McntoY-eWaRDI047FWFqj7pVlw2nBfkwz7w=s88-c-k-c0x00ffffff-no-rj",
    description:
      "In his talk, Josh shares how having his first child inspired him to approach learning in a whole new way.",
    isFeatured: false,
    isTrending: true,
  },
  {
    _id: "Wo5dMEP_BbM",
    title: "How to Get Your Brain to Focus | Chris Bailey",
    youtubeId: "Hu4Yvq-g7_Y",
    videoLength: "15:56",
    thumbnail: imageTwelve,
    likes: "291K",
    views: "12.5M",
    subscribers: "40M",
    category: "learning",
    channelName: "TedX",
    channelLink: "https://www.youtube.com/channel/UCsT0YIqwnpJCM-mx7-gSA4Q",
    channelLogo:
      "https://yt3.ggpht.com/ytc/AKedOLQGnY6McntoY-eWaRDI047FWFqj7pVlw2nBfkwz7w=s88-c-k-c0x00ffffff-no-rj",
    description:
      "The latest research is clear: the state of our attention determines the state of our lives. So how do we harness our attention to focus deeper, get distracted less, and even become more creative? ",
    isFeatured: false,
    isTrending: true,
  },
];
